services:
  Port: :3000
  FileUrl: fileservice:4000
  AuthUrl: authservice:50051
  UserUrl: userservice:50052
  CourseUrl: courseservice:50053
  CartUrl: cartservice:50054
  CategoryUrl: localhost:50054
  TopicUrl: localhost:50055
  PaymentUrl: paymentservice:4002
  Secret: go-courses
  MigrationURL: file://migrations
  AccessTokenExpiredIn: 24
  RefreshTokenExpiredIn: 720
mysql:
  Host: containers-us-west-140.railway.app
  Port: 6955
  User: root
  Password: zzrw2PZHvhRgvbGzxsC1
  DBName: railway
