services:
  Port: :3000
  AuthUrl: localhost:50051
  UserUrl: localhost:50052
  CourseUrl: localhost:50053
  CategoryUrl: localhost:50054
  TopicUrl: localhost:50055
  Secret: go-courses
  AccessTokenExpiredIn: 24
  RefreshTokenExpiredIn: 720

